/**
 * Coordinator prompt compiler — transforms the export context IR
 * into a coordinator prompt markdown string within token budget.
 */

import type {
  SquadExportContext,
  CompileCoordinatorPromptOptions,
  CompiledCoordinatorPrompt,
  SquadMemberSummary,
} from './types.js';

const LAZY_LOAD_MEMBER_THRESHOLD = 8;
const LAZY_LOAD_ROSTER_TOKEN_THRESHOLD = 3000;

/**
 * Approximate token count using char/4 heuristic.
 */
export function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

function measureSections(markdown: string): Array<{ name: string; tokens: number }> {
  const sections: Array<{ name: string; tokens: number }> = [];
  const parts = markdown.split(/^## /m);

  // First part is preamble (identity/comments)
  if (parts[0]) {
    sections.push({ name: 'preamble', tokens: estimateTokens(parts[0]) });
  }

  for (const part of parts.slice(1)) {
    const nameMatch = part.match(/^(.+)\n/);
    const name = nameMatch?.[1]?.trim() ?? 'unknown';
    sections.push({ name, tokens: estimateTokens(part) });
  }

  return sections;
}

function renderRosterFull(members: SquadMemberSummary[]): string {
  return members.map(m => {
    const summary = m.charterSummary ? ` ${m.charterSummary}` : '';
    return `- **${m.displayName}** (\`${m.slug}\`) — ${m.role}.${summary ? ` Use for${summary.startsWith(' ') ? summary : ' ' + summary}.` : ''}`;
  }).join('\n');
}

function renderRosterCompact(members: SquadMemberSummary[]): string {
  return members.map(m =>
    `- **${m.displayName}** (\`${m.slug}\`) — ${m.role}.`
  ).join('\n');
}

function renderRosterLazyLoad(members: SquadMemberSummary[]): string {
  const roster = members.map(m =>
    `- **${m.displayName}** (\`${m.slug}\`) — ${m.role}. Charter: \`${m.charterPath}\``
  ).join('\n');

  return roster + '\n\n> **Note:** Before dispatching any specialist, read their charter file for detailed scope and boundaries.';
}

function renderDispatchRules(context: SquadExportContext): string {
  const lines: string[] = [];

  for (const rule of context.routing.rules) {
    lines.push(`- If the request is mainly about ${rule.workType.toLowerCase()}, route to \`${rule.routeTo.toLowerCase()}\`.`);
  }

  if (context.routing.fallback) {
    lines.push(`- For ambiguous or multi-domain requests, ${context.routing.fallback}.`);
  } else if (context.team.members.length > 0) {
    // Default fallback to first member (typically the lead)
    const lead = context.team.members[0]!;
    lines.push(`- If the request is multi-domain, ambiguous, or strategic, route through \`${lead.slug}\` first.`);
  }

  // Add principles as dispatch hints
  for (const principle of context.routing.principles) {
    lines.push(`- ${principle}`);
  }

  return lines.join('\n');
}

function renderCeremonies(context: SquadExportContext): string {
  if (context.ceremonies.length === 0) return '';

  const lines = context.ceremonies.map(c => {
    let desc = `- **${c.name}** — trigger ${c.trigger.toLowerCase().startsWith('when') ? '' : 'when '}${c.trigger.toLowerCase()}.`;
    return desc;
  });

  return lines.join('\n');
}

function renderMemoryBootstrap(context: SquadExportContext): string {
  return context.memoryBootstrap.steps
    .map((step, i) => `${i + 1}. ${step}`)
    .join('\n');
}

function renderDispatchProtocol(context: SquadExportContext): string {
  return context.dispatch.protocol
    .map((step, i) => `${i + 1}. ${step}`)
    .join('\n');
}

function renderFullPrompt(context: SquadExportContext): string {
  const sections: string[] = [];

  // Provenance comments
  sections.push([
    `<!-- generated by squad export: do not edit by hand -->`,
    `<!-- source: ${context.sourceFiles.join(', ')} -->`,
    `<!-- generated-at: ${context.generatedAt} -->`,
    '',
    `You are **Squad (Coordinator)** — the exported coordinator for this repository.`,
  ].join('\n'));

  // Mission
  sections.push([
    '## Mission',
    '',
    '- Represent the project\'s Squad roster inside Copilot custom-agent surfaces.',
    '- Coordinate specialists using the repository\'s `.squad/` configuration.',
    '- Preserve routing, ceremony triggers, and validation behavior during delegation.',
    '- Produce assembled results for the user after delegated work completes.',
  ].join('\n'));

  // Operating mode
  sections.push([
    '## Operating mode',
    '',
    '- You are a **dispatcher first**.',
    '- Prefer specialist delegation over doing domain work inline.',
    '- Use direct answers only for trivial factual questions that do not benefit from dispatch.',
    '- Launch parallel work when tasks are independent.',
    '- Preserve validation and fact-check gates for recommendations and externally visible documents.',
  ].join('\n'));

  // Team roster
  const rosterContent = renderRosterFull(context.team.members);
  sections.push([
    '## Team roster',
    '',
    rosterContent,
  ].join('\n'));

  // Dispatch rules
  const dispatchRules = renderDispatchRules(context);
  if (dispatchRules) {
    sections.push([
      '## Dispatch rules',
      '',
      dispatchRules,
    ].join('\n'));
  }

  // Ceremony triggers
  const ceremonies = renderCeremonies(context);
  if (ceremonies) {
    sections.push([
      '## Ceremony triggers',
      '',
      ceremonies,
    ].join('\n'));
  }

  // Memory bootstrap
  sections.push([
    '## Memory bootstrap',
    '',
    'At session start, bootstrap context from repository files rather than assuming persistent runtime memory:',
    '',
    renderMemoryBootstrap(context),
  ].join('\n'));

  // Dispatch protocol
  sections.push([
    '## Dispatch protocol',
    '',
    'When delegating:',
    '',
    renderDispatchProtocol(context),
  ].join('\n'));

  // Output rules
  sections.push([
    '## Output rules',
    '',
    '- Acknowledge work in human terms before launching specialists.',
    '- Say who is working on what.',
    '- Preserve fact-check and review gates when the task includes recommendations or externally visible artifacts.',
    '- Present final answers as assembled outcomes, not raw delegated fragments.',
  ].join('\n'));

  return sections.join('\n\n');
}

function renderCompactPrompt(context: SquadExportContext): string {
  // Same structure but with compact roster
  const sections: string[] = [];

  sections.push([
    `<!-- generated by squad export: do not edit by hand -->`,
    `<!-- source: ${context.sourceFiles.join(', ')} -->`,
    `<!-- generated-at: ${context.generatedAt} -->`,
    '',
    `You are **Squad (Coordinator)** — the exported coordinator for this repository.`,
  ].join('\n'));

  sections.push([
    '## Mission',
    '',
    '- Coordinate specialists using the repository\'s `.squad/` configuration.',
    '- Route work to the right specialist. Preserve ceremonies and reviewer gates.',
  ].join('\n'));

  sections.push([
    '## Operating mode',
    '',
    '- Dispatcher first. Prefer delegation over inline work.',
    '- Launch parallel work when tasks are independent.',
  ].join('\n'));

  const rosterContent = renderRosterCompact(context.team.members);
  sections.push([
    '## Team roster',
    '',
    rosterContent,
  ].join('\n'));

  const dispatchRules = renderDispatchRules(context);
  if (dispatchRules) {
    sections.push(['## Dispatch rules', '', dispatchRules].join('\n'));
  }

  const ceremonies = renderCeremonies(context);
  if (ceremonies) {
    sections.push(['## Ceremony triggers', '', ceremonies].join('\n'));
  }

  sections.push([
    '## Memory bootstrap',
    '',
    renderMemoryBootstrap(context),
  ].join('\n'));

  sections.push([
    '## Dispatch protocol',
    '',
    'When delegating:',
    '',
    renderDispatchProtocol(context),
  ].join('\n'));

  sections.push([
    '## Output rules',
    '',
    '- Acknowledge work before dispatching. Say who is working on what.',
    '- Preserve review gates. Present final assembled outcomes.',
  ].join('\n'));

  return sections.join('\n\n');
}

function renderLazyLoadPrompt(context: SquadExportContext): string {
  const sections: string[] = [];

  sections.push([
    `<!-- generated by squad export: do not edit by hand -->`,
    `<!-- source: ${context.sourceFiles.join(', ')} -->`,
    `<!-- generated-at: ${context.generatedAt} -->`,
    '',
    `You are **Squad (Coordinator)** — the exported coordinator for this repository.`,
  ].join('\n'));

  sections.push([
    '## Mission',
    '',
    '- Coordinate specialists using the repository\'s `.squad/` configuration.',
    '- Route work to the right specialist. Preserve ceremonies and reviewer gates.',
  ].join('\n'));

  sections.push([
    '## Operating mode',
    '',
    '- Dispatcher first. Prefer delegation over inline work.',
    '- Before dispatching, read the target agent\'s charter from `.squad/agents/<slug>/charter.md`.',
    '- Launch parallel work when tasks are independent.',
  ].join('\n'));

  const rosterContent = renderRosterLazyLoad(context.team.members);
  sections.push(['## Team roster', '', rosterContent].join('\n'));

  const dispatchRules = renderDispatchRules(context);
  if (dispatchRules) {
    sections.push(['## Dispatch rules', '', dispatchRules].join('\n'));
  }

  const ceremonies = renderCeremonies(context);
  if (ceremonies) {
    sections.push(['## Ceremony triggers', '', ceremonies].join('\n'));
  }

  sections.push(['## Memory bootstrap', '', renderMemoryBootstrap(context)].join('\n'));

  sections.push([
    '## Dispatch protocol',
    '',
    'When delegating:',
    '',
    '1. Read the target agent\'s charter file for scope and boundaries.',
    '2. Pass the user\'s goal, repository context, and relevant findings.',
    '3. Ask for concrete deliverables.',
    '4. Launch independent work in parallel.',
    '5. Synthesize the returned work into one response for the user.',
  ].join('\n'));

  sections.push([
    '## Output rules',
    '',
    '- Acknowledge work before dispatching. Say who is working on what.',
    '- Preserve review gates. Present final assembled outcomes.',
  ].join('\n'));

  return sections.join('\n\n');
}

function shouldUseLazyLoad(context: SquadExportContext): boolean {
  if (context.team.members.length > LAZY_LOAD_MEMBER_THRESHOLD) return true;
  const rosterText = renderRosterFull(context.team.members);
  return estimateTokens(rosterText) > LAZY_LOAD_ROSTER_TOKEN_THRESHOLD;
}

function buildBudgetFailureMessage(
  estimate: number,
  hardLimit: number,
  sections: Array<{ name: string; tokens: number }>,
  appliedCompactions: string[],
): string {
  const top5 = [...sections].sort((a, b) => b.tokens - a.tokens).slice(0, 5);
  const topList = top5.map(s => `  - ${s.name}: ~${s.tokens} tokens`).join('\n');
  const compactList = appliedCompactions.length > 0
    ? `Compaction passes applied: ${appliedCompactions.join(', ')}`
    : 'No compaction passes applied.';

  return [
    `Export aborted: generated coordinator prompt is ~${estimate} tokens (hard cap: ${hardLimit}).`,
    `Largest sections:`,
    topList,
    compactList,
    `Try: --compact, --skills none, or split this team into multiple exported coordinators.`,
  ].join('\n');
}

/**
 * Compile the coordinator prompt from export context.
 */
export function compileCoordinatorPrompt(
  context: SquadExportContext,
  options: CompileCoordinatorPromptOptions,
): CompiledCoordinatorPrompt {
  const appliedCompactions: string[] = [];
  let draft: string;
  let estimate: number;

  if (options.compact) {
    draft = renderCompactPrompt(context);
    appliedCompactions.push('forced-compact');
  } else {
    draft = renderFullPrompt(context);
  }

  estimate = estimateTokens(draft);

  // Compaction pass 1: switch to compact mode
  if (estimate > options.softLimit && !options.compact) {
    draft = renderCompactPrompt(context);
    appliedCompactions.push('compact-charters');
    estimate = estimateTokens(draft);
  }

  // Compaction pass 2: lazy-load mode for large teams
  if (estimate > options.softLimit && shouldUseLazyLoad(context)) {
    draft = renderLazyLoadPrompt(context);
    appliedCompactions.push('lazy-load-roster');
    estimate = estimateTokens(draft);
  }

  // Hard fail
  if (estimate > options.hardLimit) {
    const sections = measureSections(draft);
    throw new Error(buildBudgetFailureMessage(estimate, options.hardLimit, sections, appliedCompactions));
  }

  const mode = appliedCompactions.includes('lazy-load-roster')
    ? 'lazy-load' as const
    : appliedCompactions.includes('compact-charters') || appliedCompactions.includes('forced-compact')
      ? 'compact' as const
      : 'full' as const;

  return {
    markdown: draft,
    estimatedTokens: estimate,
    appliedCompactions,
    sectionSizes: measureSections(draft),
    mode,
  };
}
