/**
 * File writer for the coordinator agent export.
 * Handles write, check, dry-run, and legacy collision detection.
 */

import fs from 'node:fs';
import path from 'node:path';

export interface WriteOptions {
  root: string;
  outputPath: string;
  output: string;
  check: boolean;
  dryRun: boolean;
  force: boolean;
  cleanLegacyAgent: boolean;
}

export interface WriteResult {
  written: boolean;
  driftDetected: boolean;
  legacyCollision: boolean;
  legacyCleaned: boolean;
  outputPath: string;
}

const GENERATED_MARKER = '<!-- generated by squad export: do not edit by hand -->';

/**
 * Check if an existing file was generated by squad export.
 */
function isSquadGenerated(filePath: string): boolean {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    return content.includes(GENERATED_MARKER);
  } catch {
    return false;
  }
}

/**
 * Detect legacy squad.agent.md file.
 */
function detectLegacyAgentFile(root: string): string | null {
  const candidates = [
    path.join(root, '.github', 'agents', 'squad.agent.md'),
  ];

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      return candidate;
    }
  }

  return null;
}

/**
 * Write the coordinator agent file with safety checks.
 */
export function writeCoordinatorAgent(options: WriteOptions): WriteResult {
  const { root, outputPath, output, check, dryRun, force, cleanLegacyAgent } = options;
  const fullOutputPath = path.isAbsolute(outputPath)
    ? outputPath
    : path.join(root, outputPath);

  const result: WriteResult = {
    written: false,
    driftDetected: false,
    legacyCollision: false,
    legacyCleaned: false,
    outputPath: fullOutputPath,
  };

  // Check for legacy file collision
  const legacyPath = detectLegacyAgentFile(root);
  if (legacyPath) {
    result.legacyCollision = true;

    if (cleanLegacyAgent) {
      const backupPath = legacyPath + '.bak';
      fs.renameSync(legacyPath, backupPath);
      result.legacyCleaned = true;
    }
  }

  // Check mode: compare without writing
  if (check) {
    try {
      const existing = fs.readFileSync(fullOutputPath, 'utf-8');
      result.driftDetected = existing !== output;
    } catch {
      // File doesn't exist = drift
      result.driftDetected = true;
    }
    return result;
  }

  // Dry-run mode: print but don't write
  if (dryRun) {
    process.stdout.write(output);
    return result;
  }

  // Safety: don't overwrite user-owned files unless --force
  if (fs.existsSync(fullOutputPath) && !isSquadGenerated(fullOutputPath) && !force) {
    throw new Error(
      `${fullOutputPath} exists and was not generated by squad export. ` +
      `Use --force to overwrite or remove it manually.`
    );
  }

  // Ensure directory exists
  const dir = path.dirname(fullOutputPath);
  fs.mkdirSync(dir, { recursive: true });

  // Write the file
  fs.writeFileSync(fullOutputPath, output, 'utf-8');
  result.written = true;

  return result;
}
